abstract: 'A file (with name, and other metadata) you can BLOBify'
author: 'Adam Kennedy <adam@phase-n.com>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.52
license: perl
name: File-BLOB
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  File::Basename: 0
  File::Type: 0
  Params::Util: 0.10
  Storable: 0
  bytes: 0
  perl: 5.005
version: 0.03
