---
abstract: 'A file (with name, and other metadata) you can BLOBify'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: File::BLOB
name: File-BLOB
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Type: 0.22
  IO::File: 0
  Params::Util: 0.10
  Storable: 2.16
  bytes: 0
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/File-BLOB
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/File-BLOB
version: 1.08
